# disable some
- { repo: norcalli/nvim-colorizer.lua, if: 0 }
- { repo: t9md/vim-choosewin, if: 0 }
- { repo: mattn/emmet-vim, if: 0 }
- { repo: andersevenrud/compe-tmux, if: 0 }

# use vim-illuminate over vim-cursorword
- { repo: itchyny/vim-cursorword, if: 0 }
- { repo: RRethy/vim-illuminate }

# use neorg instead of orgmode
- { repo: kristijanhusak/orgmode.nvim, if: 0 }
- repo: nvim-neorg/neorg
  on_ft: norg
  depends: [ nvim-treesitter, telescope.nvim, plenary.nvim ]
  hook_source: lua require('neorg').setup({ load = { ["core.defaults"] = {} } })

# my completion sources
- { repo: hrsh7th/cmp-calc, on_source: nvim-cmp }

- { repo: jose-elias-alvarez/null-ls.nvim, on_source: nvim-lspconfig }
- { repo: jose-elias-alvarez/nvim-lsp-ts-utils, on_source: nvim-lspconfig }

- { repo: wellle/targets.vim, on_event: [ CursorMoved ] }

- repo: xiyaowong/telescope-emoji.nvim
  if: has('nvim-0.5')
  on_source: telescope.nvim
  hook_source: lua require('telescope').load_extension('emoji')

# modify to always splitjoin_trailing_comma
- repo: AndrewRadev/splitjoin.vim
  rev: main
  on_map: { n: <Plug>Splitjoin }
  hook_add: |-
    let g:splitjoin_join_mapping = ''
    let g:splitjoin_split_mapping = ''
    let b:splitjoin_trailing_comma = 1

# add my own
- repo: tpope/vim-unimpaired
- { repo: LnL7/vim-nix, on_ft: nix }

- { repo: deris/vim-shot-f, if: 0 }
- { repo: ggandor/lightspeed.nvim, on_map: { n: ['s', 'S', 'f', 't', 'F', 'T'] } }

- repo: kana/vim-altr
  on_map: { n: <Plug> }
  hook_source: call altr#define('%.ts', '%.test.ts')

- repo: arthurxavierx/vim-caser
  on_map: { nx: ',c' }
  hook_add: |-
    let g:caser_prefix = ',c'

# DAP
- repo: mfussenegger/nvim-dap
  if: has('nvim-0.5')
  on_event: VimEnter
  lazy: 1
  hook_post_source: lua require('plugins.dap').setup()
- repo: leoluz/nvim-dap-go
  on_source: nvim-dap
# - repo: theHamsta/nvim-dap-virtual-text
#   on_source: nvim-dap
#   hook_post_source: lua require('nvim-dap-virtual-text').setup()
